#ifndef TEST_CNC_MODULES_PLANNER_H
#define TEST_CNC_MODULES_PLANNER_H

void test_junctionFeedRateInMmPerS_notValidLines();
void test_junctionFeedRateInMmPerS_0Deg();
void test_junctionFeedRateInMmPerS_45Deg();
void test_junctionFeedRateInMmPerS_90Deg();
void test_junctionFeedRateInMmPerS_135Deg();
void test_junctionFeedRateInMmPerS_180Deg();

void test_PlannerBlockFromLine_invalid();
void test_PlannerBlockFromLine_directions();
void test_PlannerBlockFromLine_spindleRpm();
void test_PlannerBlockFromLine_noMovement();
void test_PlannerBlockFromLine_accelerationOnly();
void test_PlannerBlockFromLine_decelerationOnly();
void test_PlannerBlockFromLine_accelerationPlateau();
void test_PlannerBlockFromLine_plateauDeceleration();
void test_PlannerBlockFromLine_plateau();
void test_PlannerBlockFromLine_accelerationPlateauDeceleration();
void test_PlannerBlockFromLine_accelerationDeceleration1();
void test_PlannerBlockFromLine_accelerationDeceleration2();

void test_PlannerBlockToLinearBlock_directions();
void test_PlannerBlockToLinearBlock_spindleRpm();
void test_PlannerBlockToLinearBlock_noMovement();
void test_PlannerBlockToLinearBlock_accelerationOnly();
void test_PlannerBlockToLinearBlock_decelerationOnly();
void test_PlannerBlockToLinearBlock_accelerationPlateau();
void test_PlannerBlockToLinearBlock_plateauDeceleration();
void test_PlannerBlockToLinearBlock_plateau();
void test_PlannerBlockToLinearBlock_accelerationPlateauDeceleration();
void test_PlannerBlockToLinearBlock_accelerationDeceleration();

#endif
